# Docker Compose para testes automatizados
# Este arquivo é usado para executar testes em ambiente isolado

version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: financeinfo_postgres_test
    environment:
      POSTGRES_DB: financeinfo_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    networks:
      - test_network
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d financeinfo_test"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-test:
    image: redis:7-alpine
    container_name: financeinfo_redis_test
    command: redis-server --requirepass test_password
    ports:
      - "6380:6379"
    networks:
      - test_network
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "test_password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  test_network:
    driver: bridge