version: '3.8'

services:
  # PostgreSQL 15 Database
  postgres:
    image: postgres:15-alpine
    container_name: financeinfo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: financeinfo_dev
      POSTGRES_USER: financeinfo_user
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - financeinfo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeinfo_user -d financeinfo_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 7 Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: financeinfo_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass dev_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - financeinfo_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "dev_redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Database Management - Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: financeinfo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@financeinfo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - financeinfo_network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tools

  # Redis Commander (Redis Management - Optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: financeinfo_redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:dev_redis_password
      HTTP_USER: admin
      HTTP_PASSWORD: admin123
    ports:
      - "8081:8081"
    networks:
      - financeinfo_network
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  financeinfo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16