# Docker Compose Override for Development
# This file extends docker-compose.yml with development-specific configurations
# It's automatically merged when running docker-compose commands

version: '3.8'

services:
  postgres:
    # Development optimizations
    command: postgres -c log_statement=all -c log_destination=stderr -c log_min_messages=info
    environment:
      # Enable more verbose logging for development
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C --auth-local=trust --auth-host=md5"
    volumes:
      # Mount local SQL files for easy development
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations:ro
      - ./database/seeds:/docker-entrypoint-initdb.d/seeds:ro
    
  redis:
    # Development configuration with more verbose logging
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel debug
    
  # Development database browser (optional)
  adminer:
    image: adminer:latest
    container_name: financeinfo_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    networks:
      - financeinfo_network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tools